name: microcloud
base: core22
assumes:
 - snapd2.59
version: "1.1"
grade: stable
source-code: https://github.com/canonical/microcloud.git
summary: Fully automated private clouds
description: |-
 Fully automated private clouds.

confinement: strict

apps:
  # Service
  daemon:
    command: commands/daemon.start
    daemon: simple
    plugs:
      - lxd
      - microceph
      - microovn
      - network
      - network-bind

  # Commands
  microcloud:
    command: commands/microcloud
    plugs:
      - network

parts:
  dqlite:
    build-attributes: [core22-step-dependencies]
    after:
      - raft
    source: https://github.com/canonical/dqlite
    source-tag: v1.16.0
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libsqlite3-0
      - libuv1
    build-packages:
      - libsqlite3-dev
      - libuv1-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libdqlite*so*
      - lib/*/libuv*

  raft:
    build-attributes: [core22-step-dependencies]
    source: https://github.com/canonical/raft
    source-tag: v0.18.0
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libuv1
      - liblz4-1
    build-packages:
      - libuv1-dev
      - liblz4-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libraft*so*
      - lib/*/libuv.so*

  microcloud:
    build-attributes: [core22-step-dependencies]
    source: https://github.com/canonical/microcloud
    source-commit: 4b02c16672e22c41ff7515d10717f373b6a25349 # MicroCloud 1.1
    source-type: git
    after:
      - dqlite
    build-snaps:
      - go
    plugin: nil
    override-pull: |
      snapcraftctl pull
      set -ex

      # Download the dependencies
      cd microcloud
      go get -d -v -tags=agent ./...
    override-build: |
      set -ex

      git config user.email "noreply@lists.canonical.com"
      git config user.name "MicroCloud snap builder"

      git cherry-pick e50cd006e8773a3dfaa020c9997eb7789253ee15 # microcloud/cmd/microcloud: Use stdin for preseed.yaml
      git cherry-pick b1553cb2f3ea111fb497e1d60cec7b3eec9680c6 # microcloud/test/suites: Rename conflicting variable name
      git cherry-pick b19d1b537e9b9099bb5ddd2f8643ec302a4d1b54 # microcloud/test/includes: Default to edge snap if local one not provided
      git cherry-pick 404827f070282e47f3a033638587f460dd5c034a # microcloud/test/includes: Fix instance removal between tests
      git cherry-pick 00d6fca0db2503f29477ea124162ba7a267ba69f # microcloud/service: Add ZFS pool description
      git cherry-pick 6700eabb7ce0dfe4fb3c3d95fad7e260e4486a66 # microcloud/mdns: Include net.Interface in NetworkInfo
      git cherry-pick 201968ec5191d7ddfecca700be6c1efdd58b49c9 # microcloud/mdns: Pass the interface to the mdns handler
      git cherry-pick 71567eadb4192fd1242820584069c29077f7fd7c # microcloud/cmd/microcloud: Pass network interface through initial networking questions
      git cherry-pick 283efac02aeea6006c39201b939bb774e426bdfe # microcloud/cmd/microcloud: Update usages of askAddress and NetworkInfo
      git cherry-pick 4e0da91debc563c8eb5cfbc3170d1dd0d13de7ba # microcloud/cmd/microcloud: Add option to specify interface in preseed
      git cherry-pick 88c7ef73819f2a01e7e7161d685f50860a1b1072 # microcloud/test/suites: Update preseed test
      git cherry-pick a8584be34dea149e736a2c8e9a1d902523911618 # microcloud/test/includes: Fix typo in testsuite
      git cherry-pick f19707ad48062c350947a3b432a1e6a6022c638e # microcloud/service: Properly broadcast available interfaces over those interfaces

      # Setup build environment
      export CGO_CFLAGS="-I${SNAPCRAFT_STAGE}/include/ -I${SNAPCRAFT_STAGE}/usr/local/include/"
      export CGO_LDFLAGS="-L${SNAPCRAFT_STAGE}/lib/ -L${SNAPCRAFT_STAGE}/usr/local/lib/"
      export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

      # Build the binaries
      cd microcloud
      go build -o "${SNAPCRAFT_PART_INSTALL}/bin/microcloud" -tags=agent ./cmd/microcloud
      go build -o "${SNAPCRAFT_PART_INSTALL}/bin/microcloudd" -tags=agent,libsqlite3 ./cmd/microcloudd
    prime:
      - bin/microcloud
      - bin/microcloudd

  wrappers:
    plugin: dump
    source: snapcraft/
